---
plan_slug: standard-2
triggers:
- event: branch
  branch_name: main
- event: pull_request
commands:
- checkout
- packages-command
- addons-command
- cache restore
- bundle install --deployment --path vendor/bundle
- cache store
- bundle exec rake db:setup
- test-command
